name: Deploy Documentation and Landing Page

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - id: pages
        name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Select Xcode 15.1
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.1.0'
      
      - name: Build DocC
        run: |
          # Build documentation
          swift package resolve
          xcodebuild docbuild -scheme StarCraftKit -derivedDataPath /tmp/docbuild -destination 'generic/platform=iOS'
          
          # Process documentation archive
          $(xcrun --find docc) process-archive \
            transform-for-static-hosting /tmp/docbuild/Build/Products/Debug-iphoneos/StarCraftKit.doccarchive \
            --output-path docs-temp \
            --hosting-base-path 'StarCraftKit'
          
          # Create deployment directory structure
          mkdir -p deployment/StarCraftKit
          
          # Copy landing page assets
          cp -r docs/* deployment/ 2>/dev/null || true
          
          # Copy documentation to subdirectory
          cp -r docs-temp/* deployment/StarCraftKit/
          
          # Clean up
          rm -rf docs-temp
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'deployment'
      
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4