name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'  # Triggers on version tags like 2.0.0

jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            name: macOS
            build-script: |
              # Build for each architecture separately, then combine
              swift build -c release --arch arm64 --product starcraft-cli
              swift build -c release --arch x86_64 --product starcraft-cli
              
              # Create universal binary
              lipo -create \
                .build/arm64-apple-macosx/release/starcraft-cli \
                .build/x86_64-apple-macosx/release/starcraft-cli \
                -output .build/release/starcraft-cli
              
              # Make it executable
              chmod +x .build/release/starcraft-cli
          - os: ubuntu-latest
            name: Linux
            build-script: |
              swift build -c release --static-swift-stdlib --product starcraft-cli
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.9.2"
      
      - name: Cache SPM dependencies
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      
      - name: Build release binary
        run: |
          echo "Building for ${{ matrix.name }}"
          ${{ matrix.build-script }}
      
      - name: Create distribution
        run: |
          mkdir -p dist
          cp .build/release/starcraft-cli dist/
          ARCHIVE_NAME="StarCraftKit-${{ matrix.name }}-${{ github.ref_name }}.tar.gz"
          tar -czf "$ARCHIVE_NAME" -C dist .
          
          # Generate checksum
          if [ "${{ runner.os }}" == "macOS" ]; then
            shasum -a 256 *.tar.gz > "StarCraftKit-${{ matrix.name }}-${{ github.ref_name }}.sha256"
          else
            sha256sum *.tar.gz > "StarCraftKit-${{ matrix.name }}-${{ github.ref_name }}.sha256"
          fi
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: StarCraftKit-${{ matrix.name }}
          path: |
            *.tar.gz
            *.sha256

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: List artifacts
        run: |
          echo "Downloaded artifacts:"
          find artifacts -type f -name "*" | sort
      
      - name: Generate release notes
        id: release_notes
        run: |
          # Extract version number
          VERSION="${GITHUB_REF#refs/tags/}"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          
          # Generate simple release notes
          cat > release-notes.md << EOF
          # StarCraftKit $VERSION

          ## Installation

          ### macOS

          \`\`\`bash
          curl -L https://github.com/${{ github.repository }}/releases/download/$VERSION/StarCraftKit-macOS-$VERSION.tar.gz | tar xz
          chmod +x starcraft-cli
          sudo mv starcraft-cli /usr/local/bin/
          \`\`\`

          ### Linux

          \`\`\`bash
          curl -L https://github.com/${{ github.repository }}/releases/download/$VERSION/StarCraftKit-Linux-$VERSION.tar.gz | tar xz
          chmod +x starcraft-cli
          sudo mv starcraft-cli /usr/local/bin/
          \`\`\`

          ## Checksums

          Verify your download with the provided SHA256 checksums.
          EOF
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          name: StarCraftKit ${{ steps.release_notes.outputs.VERSION }}
          body_path: release-notes.md
          generate_release_notes: true
          files: |
            artifacts/**/*.tar.gz
            artifacts/**/*.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}