name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.9"
      - run: swift build -c release --product starcraft-cli
      - run: |
          mkdir -p dist
          cp .build/release/starcraft-cli dist/
          tar -czf starcraft-cli-macos.tar.gz -C dist .
      - uses: actions/upload-artifact@v4
        with:
          name: starcraft-cli-macos
          path: starcraft-cli-macos.tar.gz

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker run --rm -v "$PWD:/workspace" -w /workspace swift:5.9 \
            swift build -c release --static-swift-stdlib --product starcraft-cli
          mkdir -p dist
          cp .build/release/starcraft-cli dist/
          tar -czf starcraft-cli-linux.tar.gz -C dist .
      - uses: actions/upload-artifact@v4
        with:
          name: starcraft-cli-linux
          path: starcraft-cli-linux.tar.gz

  release:
    needs: [build-macos, build-linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*.tar.gz
          generate_release_notes: true
          token: ${{ secrets.GH_TOKEN }}